# ============================================================
# CONFIGURAÇÃO DO ECLIPSE MOSQUITTO
# ============================================================

# Porta padrão utilizada pelo MQTT.
listener 1883

# Permite conexões sem usuário e senha.
# Isso é adequado para o protótipo acadêmico.
allow_anonymous true